---
title: "Data Manipulation"
output: github_document
---

```{r}
library(tidyverse)
```

Import FAS litters and pups.

```{r}
litters_df <- read_csv("data/FAS_litters.csv")
litters_df <- janitor::clean_names(litters_df)

pups_df <- read_csv("data/FAS_pups.csv")
pups_df <- janitor::clean_names(pups_df)
```


## `select`

`select` is used to select columns
```{r}
select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group, litter_number, gd0_weight)

select(litters_df, group, litter_number, gd0_weight:gd_of_birth) # ":" allows you to select things in between

select(litters_df, group, starts_with("pups")) # select all variables that starts with "pups"
# other options: ends_with(), contains(), see ?select

select(litters_df, -starts_with("gd")) # removes those that start with "gd"

select(litters_df, group, litter_id=litter_number) # rename variable

select(litters_df, group, litter_id=litter_number, everything()) # keep everything else

select(litters_df, gd0_weight, everything()) # give "gd0_weight" first and keep everything after
```

```{r}
rename(litters_df, litter_id = litter_number) # alternative to changing variable name with select() + everything()

relocate(litters_df, litter_number) # change column positions
```

```{r}
select(pups_df, litter_number:pd_ears)
```

## `filter`

Get rid of/choose rows using `filter`.

```{r}
filter(litters_df, group == "Con7") # choose rows that are in the Con7 group
filter(litters_df, group == "Mod8")
# other operators include ==,<=,>=,!-, etc.

filter(litters_df, gd0_weight > 20)

filter(litters_df, group == "Con7" | group == "Con8") # | means or, select con7 or con8 groups
filter(litters_df, group %in% c("Con7", "Con8"))

filter(litters_df, !(group == "Con7"))

filter(litters_df, !(group == "Con7"), gd0_weight > 20) # can combine multiple together
```

What about missing rows? Instead of using `filter()`, can use `drop_na`:

```{r}
drop_na(litters_df) # drop all NAs in the dataframe
drop_na(litters_df, gd0_weight) # only drop NAs in the gd0_weight variable
```


## `mutate`

This is used to add or change variables

```{r}
mutate(litters_df, wt_gain = gd18_weight - gd0_weight) # calculates weight gain through two other variables in the dataset
mutate(litters_df, group = str_to_lower(group)) # changes "group" to lower case
mutate(litters_df, 
       wt_gain = gd18_weight - gd0_weight, 
       group = str_to_lower(group)) # can add as many mutate lines together
```

## `arrange()`

```{r}
arrange(litters_df, gd0_weight) # arranges by the order of gd0_weight
arrange(litters_df, group, gd0_weight) # arrange by group first, then by gd0_weight
```

## pipes

Use the pipe operator `|>` to change together a bunch of commands

```{r}
litter_df <- 
  read_csv("data/FAS_litters.csv") |> 
  janitor::clean_names() |> 
  select(-starts_with("pups")) |> 
  mutate(
    group = str_to_lower(group),
    wt_gain = gd18_weight - gd0_weight,
  ) |> 
  drop_na(wt_gain) |> 
  arrange(group, wt_gain)
```









